import {Game} from './types/game';

export const gamesList: Game[] = [
  {id: 1, path: '/wilddragonicon.jpg', name: 'bgaming'},
  {id: 2, path: '/billyonaireicon.jpg', name: 'fishing'},
  {id: 3, path: '/paradiseicon.jpg', name: 'netent'},
  {id: 4, path: '/wilddiamondsicon.jpg', name: 'table'},
  {id: 5, path: '/bookoffortuneicon.jpg', name: 'wazdan'},
  {id: 6, path: '/ultrasevenicon.jpg', name: 'racing'},
  {id: 7, path: '/billysgameicon.jpg', name: 'novomatic'},
  {id: 8, path: '/bookofaztecicon.jpg', name: 'amatic'},
  {id: 9, path: '/ironchickenhuntericon.jpg', name: 'bgaming'},
  {id: 10, path: '/ironheroicon.jpg', name: 'egt'},
  {id: 11, path: '/wilddragonicon.jpg', name: 'fishing'},
  {id: 12, path: '/billyonaireicon.jpg', name: 'wazdan'},
  {id: 13, path: '/gogomagiccaticon.jpg', name: 'racing'},
  {id: 14, path: '/gogomagicdogicon.jpg', name: 'netent'},
  {id: 15, path: '/happyanimalfarmicon.jpg', name: 'table'},
  {id: 16, path: '/gogomagicdogicon.jpg', name: 'novomatic'},
  {id: 17, path: '/gogomagiccaticon.jpg', name: 'bgaming'},
  {id: 18, path: '/ironheroicon.jpg', name: 'amatic'},
  {id: 19, path: '/ultrasevenicon.jpg', name: 'fishing'},
  {id: 20, path: '/bookofaztecicon.jpg', name: 'wazdan'},
  {id: 21, path: '/wilddiamondsicon.jpg', name: 'netent'},
  {id: 22, path: '/billysgameicon.jpg', name: 'table'},
  {id: 23, path: '/bookoffortuneicon.jpg', name: 'racing'},
  {id: 24, path: '/ironchickenhuntericon.jpg', name: 'novomatic'},
  {id: 25, path: '/paradiseicon.jpg', name: 'bgaming'},
  {id: 26, path: '/wilddragonicon.jpg', name: 'fishing'},
  {id: 27, path: '/billyonaireicon.jpg', name: 'wazdan'},
  {id: 28, path: '/billyonaireicon.jpg', name: 'netent'},
  {id: 29, path: '/wilddragonicon.jpg', name: 'table'},
  {id: 30, path: '/happyanimalfarmicon.jpg', name: 'racing'},
  {id: 31, path: '/billyonaireicon.jpg', name: 'novomatic'},
  {id: 32, path: '/paradiseicon.jpg', name: 'bgaming'},
  {id: 33, path: '/wilddiamondsicon.jpg', name: 'fishing'},
];
export const sliderList: Game[] = [
  {
    id: 1,
    path: '/egt.png',
    name: 'egt',
  },
  {
    id: 2,
    path: '/fishing.png',
    name: 'fishing',
  },
  {
    id: 3,
    path: '/netent.png',
    name: 'netent',
  },
  {
    id: 4,
    path: '/table.png',
    name: 'table',
  },
  {
    id: 5,
    path: '/wazdan.png',
    name: 'wazdans',
  },
  {
    id: 6,
    path: '/racing.png',
    name: 'racing',
  },
  {
    id: 7,
    path: '/novomatic.png',
    name: 'novomatic',
  },
  {
    id: 8,
    path: '/amatic.png',
    name: 'amatic',
  },
  {
    id: 9,
    path: '/bgaming.png',
    name: 'bgaming',
  },
];
